apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data
  namespace: nexus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd-ssd
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-output
  namespace: nexus
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-nvme
  resources:
    requests:
      storage: 5Gi
