apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: nexus
spec:
  type: NodePort
  selector:
    app: nexus
  ports:
    - name: webhook
      port: 9876
      targetPort: 9876
      nodePort: 30876
      protocol: TCP
